data_science:
  nodes:
  - func: split_data
    inputs: [model_input_table, params:model_options]
    outputs: [X_train, X_test, y_train, y_test]
    name: split_data_node
  - func: train_model
    inputs: [X_train, y_train]
    outputs: [regressor]
    name: train_model_node
  - func: evaluate_model
    inputs: [regressor, X_test, y_test]
    outputs: null
    name: evaluate_model_node
